name: Build Major Packages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [main]
    paths:
      - '.github/workflows/buildmajor.yml'

jobs:
  build-major-packages:
    strategy: 
      fail-fast: false
      matrix:
        swift: ['6.0', '6.1']
        os: ['macos-latest', 'ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Android Toolchain
        id: setup-toolchain-android
        uses: skiptools/swift-android-action@main
        with:
          # just set up the toolchain and don't build anything
          build-package: false
          swift-version: ${{ matrix.swift }}

      - name: Checkout swift-algorithms
        uses: actions/checkout@v4
        with:
          repository: apple/swift-algorithms
          path: swift-algorithms
      - name: Build swift-algorithms
        shell: bash
        working-directory: swift-algorithms
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout swift-crypto
        uses: actions/checkout@v4
        with:
          repository: apple/swift-crypto
          path: swift-crypto
      - name: Build swift-crypto
        shell: bash
        working-directory: swift-crypto
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout swift-numerics
        uses: actions/checkout@v4
        with:
          repository: apple/swift-numerics
          path: swift-numerics
      - name: Build swift-numerics
        shell: bash
        working-directory: swift-numerics
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout swift-system
        uses: actions/checkout@v4
        with:
          repository: apple/swift-system
          path: swift-system
      - name: Build swift-system
        shell: bash
        if: false # needs https://github.com/apple/swift-system/pull/225
        working-directory: swift-system
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout swift-collections
        uses: actions/checkout@v4
        with:
          repository: apple/swift-collections
          path: swift-collections
      - name: Build swift-collections
        shell: bash
        working-directory: swift-collections
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout swift-atomics
        uses: actions/checkout@v4
        with:
          repository: apple/swift-atomics
          path: swift-atomics
      - name: Build swift-atomics
        shell: bash
        working-directory: swift-atomics
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout swift-foundation
        uses: actions/checkout@v4
        with:
          repository: apple/swift-foundation
          path: swift-foundation
      - name: Build swift-foundation
        shell: bash
        working-directory: swift-foundation
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout swift-nio
        uses: actions/checkout@v4
        with:
          repository: apple/swift-nio
          path: swift-nio
      - name: Build swift-nio
        shell: bash
        working-directory: swift-nio
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout swift-nio-http2
        uses: actions/checkout@v4
        with:
          repository: apple/swift-nio-http2
          path: swift-nio-http2
      - name: Build swift-nio-http2
        shell: bash
        working-directory: swift-nio-http2
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout swift-nio-ssl
        uses: actions/checkout@v4
        with:
          repository: apple/swift-nio-ssl
          path: swift-nio-ssl
      - name: Build swift-nio-ssl
        if: false # error: cannot find 'open' in scope
        shell: bash
        working-directory: swift-nio-ssl
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout jpsim/Yams
        uses: actions/checkout@v4
        with:
          repository: jpsim/Yams
          path: Yams
      - name: Build jpsim/Yams
        shell: bash
        working-directory: Yams
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout tayloraswift/swift-png
        uses: actions/checkout@v4
        with:
          repository: tayloraswift/swift-png
          path: swift-png
      - name: Build tayloraswift/swift-png
        shell: bash
        working-directory: swift-png
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

      - name: Checkout vapor/vapor
        uses: actions/checkout@v4
        with:
          repository: vapor/vapor
          path: vapor
      - name: Build vapor/vapor
        shell: bash
        working-directory: vapor
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

