name: Build Major Packages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [main]
    paths:
      - '.github/workflows/buildmajor.yml'

jobs:
  buildbot:
    runs-on: macos-latest
    steps:
      - name: Setup Android Toolchain
        id: setup-toolchain-android
        uses: skiptools/swift-android-action@main
        with:
          # just set up the toolchain and don't build anything
          build-package: false
          # build with the latest 6.1
          swift-version: 6.1

      - name: Checkout swift-argument-parser
        uses: actions/checkout@v4
        with:
          repository: apple/swift-argument-parser
          path: swift-argument-parser
      - name: Build swift-argument-parser
        shell: bash
        working-directory: swift-argument-parser
        run: |
          ${{ steps.setup-toolchain-android.outputs.swift-build }} --build-tests

